# Cloud Build configuration for deploying to Cloud Run
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hospital-stress-backend:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hospital-stress-backend:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hospital-stress-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hospital-stress-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--cpu'
      - '2'
      - '--memory'
      - '4Gi'
      - '--timeout'
      - '60s'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'BIGQUERY_PROJECT_ID=$PROJECT_ID,BIGQUERY_DATASET=hospital_data,VERTEX_AI_PROJECT=$PROJECT_ID,VERTEX_AI_LOCATION=us-central1'

images:
  - 'gcr.io/$PROJECT_ID/hospital-stress-backend:$COMMIT_SHA'
